# Generated by Django 6.1 on 2026-08-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.PositiveIntegerField()),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PURSUING', 'Pursuing'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped')], default='PURSUING', max_length=10)),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.coursebatch')),
            ],
            options={
                'ordering': ['-admission_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=30, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField()),
                ('final_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('student_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='students.studentcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='students.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='students.studentprofile')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.studentcourse')),
            ],
            options={
                'ordering': ['semester__number'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='PENDING', max_length=10)),
                ('declared_date', models.DateField(blank=True, null=True)),
                ('student_semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='students.studentsemester')),
            ],
        ),
    ]
