# Generated by Django 6.1 on 2026-08-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.IntegerField()),
                ('completion_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pursuing', 'Pursuing'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('detained', 'Detained')], default='pursuing', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.course')),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.coursebatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_enrolled', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField()),
                ('final_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_record', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('backlog', 'Backlog')], default='active', max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'semester', 'academic_year'), name='unique_student_semester')],
            },
        ),
    ]
