# Generated by Django 6.1 on 2026-08-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_term', models.CharField(choices=[('mid_sem', 'Mid Semester'), ('end_sem', 'End Semester'), ('internal', 'Internal')], max_length=20)),
                ('exam_category', models.CharField(choices=[('written', 'Written'), ('practical', 'Practical'), ('presentation', 'Presentation'), ('viva', 'Viva')], max_length=20)),
                ('exam_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subjectoffering')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('regular', 'Regular'), ('retest', 'Retest'), ('improvement', 'Improvement')], default='regular', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('medical_leave', 'Medical Leave')], max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('result_status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('result_status', models.CharField(max_length=20)),
                ('declared_on', models.DateField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reports', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reports', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('offering', 'exam_term', 'exam_category', 'exam_date'), name='unique_exam_schedule'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_number'), name='unique_exam_attempt'),
        ),
        migrations.AddConstraint(
            model_name='semesterreport',
            constraint=models.UniqueConstraint(fields=('student', 'semester', 'academic_year'), name='unique_semester_report'),
        ),
        migrations.AddConstraint(
            model_name='semesterreport',
            constraint=models.CheckConstraint(condition=models.Q(('total_marks__gt', 0)), name='check_total_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='semesterreport',
            constraint=models.CheckConstraint(condition=models.Q(('obtained_marks__gte', 0)), name='check_obtained_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='semesterreport',
            constraint=models.CheckConstraint(condition=models.Q(('obtained_marks__lte', models.F('total_marks'))), name='check_marks_validity'),
        ),
        migrations.AddConstraint(
            model_name='semesterreport',
            constraint=models.CheckConstraint(condition=models.Q(('sgpa__gte', 0), ('sgpa__lte', 10)), name='check_sgpa_range'),
        ),
    ]
