# Generated by Django 6.1 on 2026-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('results_pending', 'Results Pending'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
