<<<<<<< HEAD
# Generated by Django 6.1 on 2026-08-29 12:24

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.1 on 2026-08-23 08:41

import django.db.models.deletion
>>>>>>> origin/main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/main
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='course_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.coursebatch'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_offerings', to='faculty.facultyprofile'),
=======
            model_name='subjectoffering',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_offerings', to='faculty.faculty'),
>>>>>>> origin/main
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
<<<<<<< HEAD
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academics.subjectoffering'),
        ),
        migrations.AlterUniqueTogether(
            name='coursebatch',
            unique_together={('course', 'start_year')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course_batch', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'semester')},
=======
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academics.subjectoffering'),
        ),
        migrations.AddConstraint(
            model_name='coursebatch',
            constraint=models.UniqueConstraint(fields=('course', 'academic_year'), name='unique_course_batch'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('course_batch', 'semester_number'), name='unique_semester'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('offering', 'date', 'start_time'), name='unique_lecture_slot'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_start_end_time'),
>>>>>>> origin/main
        ),
    ]
