# Generated by Django 6.1 on 2026-08-23 20:54

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[assignments.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[assignments.models.validate_pdf]),
        ),
    ]
