# Generated by Django 6.1.1 on 2026-09-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('END_TERM', 'End-term'), ('QUIZ', 'Quiz'), ('PRACTICAL', 'Practical'), ('INTERNAL', 'Internal Assessment')], max_length=15)),
                ('academic_year', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations_created', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.semester')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.course')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examination')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['course', 'semester'], name='examination_course__119a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'course'], name='examination_student_17c39d_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('student', 'examination'), name='unique_result_per_exam'),
        ),
    ]
