# Generated by Django 6.1 on 2026-08-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='course_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.coursebatch'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_offerings', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academics.subjectoffering'),
        ),
        migrations.AlterUniqueTogether(
            name='coursebatch',
            unique_together={('course', 'start_year')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course_batch', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'semester')},
        ),
    ]
