# Generated by Django 6.1 on 2026-08-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('MID_SEM', 'Mid-Sem'), ('END_SEM', 'End-Sem'), ('INTERNAL', 'Internal')], max_length=10)),
                ('category', models.CharField(choices=[('WRITTEN', 'Written'), ('PRACTICAL', 'Practical'), ('PRESENTATION', 'Presentation'), ('VIVA', 'Viva')], max_length=15)),
                ('name', models.CharField(blank=True, help_text="e.g. 'Internal Test 2' (optional label)", max_length=150)),
                ('exam_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subjectoffering')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('attempt_type', models.CharField(choices=[('REGULAR', 'Regular'), ('RETEST', 'Retest'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', max_length=15)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('MEDICAL_LEAVE', 'Medical Leave')], default='PRESENT', max_length=15)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('pass_status', models.BooleanField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-attempt_number'],
                'unique_together': {('exam', 'student', 'attempt_number')},
            },
        ),
    ]
